const photos = [
    {id: 'CB101', url: './images/1.webp', collection: 'Cool Blues', alt: 'Classic Venom suited Spider-Man'},
    {id: 'PT101', url: './images/2.webp', collection: 'Painterly', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS201', url: './images/3.webp', collection: 'Two-strip', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS102', url: './images/4.webp', collection: 'Two-strip', alt: 'Classic Venom suited Spider-Man'},
    {id: 'VA301', url: './images/5.webp', collection: 'Vanilla', alt: 'Classic Venom suited Spider-Man'},
    {id: 'VA302', url: './images/6.webp', collection: 'Vanilla', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS203', url: './images/7.webp', collection: 'Two-strip', alt: 'Classic Venom suited Spider-Man'},
    {id: 'CB102', url: './images/8.webp', collection: 'Cool Blues', alt: 'Classic Venom suited Spider-Man'},
    {id: 'VA303', url: './images/9.webp', collection: 'Vanilla', alt: 'Classic Venom suited Spider-Man'},
    {id: 'VA304', url: './images/10.webp', collection: 'Vanilla', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS204', url: './images/11.webp', collection: 'Two-strip', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS205', url: './images/12.webp', collection: 'Two-strip', alt: 'Classic Venom suited Spider-Man'},
    {id: 'CB103', url: './images/13.webp', collection: 'Cool Blues', alt: 'Classic Venom suited Spider-Man'},
    {id: 'CB104', url: './images/14.webp', collection: 'Cool Blues', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS206', url: './images/15.webp', collection: 'Two-strip', alt: 'Classic Venom suited Spider-Man'},
    {id: 'VA305', url: './images/16.webp', collection: 'Vanilla', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS207', url: './images/17.webp', collection: 'Two-script', alt: 'Classic Venom suited Spider-Man'},
    {id: 'VA306', url: './images/18.webp', collection: 'Vanilla', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS208', url: './images/19.webp', collection: 'Two-strip', alt: 'Classic Venom suited Spider-Man'},
    {id: 'VA307', url: './images/20.webp', collection: 'Vanilla', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS209', url: './images/21.webp', collection: 'Two-strip', alt: 'Classic Venom suited Spider-Man'},
    {id: 'VA308', url: './images/22.webp', collection: 'Vanilla', alt: 'Classic Venom suited Spider-Man'},
    {id: 'TS210', url: './images/23.webp', collection: 'Two-strip', alt: 'Classic Venom suited Spider-Man'},
    {id: 'CP401', url: './images/24.webp', collection: 'Cross Process', alt: 'Spider-Man wearing a winter hat and vest, and a backpack'},
    {id: 'CP402', url: './images/25.webp', collection: 'Cross Process', alt: 'Spider-Man wearing a winter hat and vest, and a backpack'},
    {id: 'CP403', url: './images/26.webp', collection: 'Cross Process', alt: 'Spider-Man wearing a winter hat and vest, and a backpack'},
    {id: 'CP404', url: './images/27.webp', collection: 'Cross Process', alt: 'Spider-Man wearing a winter hat and vest, and a backpack'},
];

export default photos;